import type { CheckCategory, Effort, Severity } from "../types/index.js";

interface AxeCatalogEntry {
  rule_id: string;
  source: "axe";
  vendor_rule_id: string | null;
  category: CheckCategory;
  default_severity: Severity;
  default_effort: Effort;
  wcag: string | null;
  title_template: string;
  description_template: string;
  recommendation: string;
}

const axeCatalog: Record<string, AxeCatalogEntry> = {
  "a11y/color-contrast": {
    rule_id: "a11y/color-contrast",
    source: "axe",
    vendor_rule_id: "color-contrast",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: "1.4.3",
    title_template: "Elements must have sufficient color contrast",
    description_template: "Text or UI components do not meet the minimum contrast ratio.",
    recommendation:
      "Increase the contrast ratio between foreground and background colors to at least 4.5:1 for normal text and 3:1 for large text.",
  },
  "a11y/image-alt": {
    rule_id: "a11y/image-alt",
    source: "axe",
    vendor_rule_id: "image-alt",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "1.1.1",
    title_template: "Images must have alternative text",
    description_template: "Images without alt text are invisible to screen reader users.",
    recommendation:
      'Add a descriptive alt attribute to each image, or alt="" for decorative images.',
  },
  "a11y/label": {
    rule_id: "a11y/label",
    source: "axe",
    vendor_rule_id: "label",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "1.3.1",
    title_template: "Form elements must have labels",
    description_template: "A form input has no associated label element.",
    recommendation:
      "Add a label element with a for attribute matching the input id, or use aria-label or aria-labelledby.",
  },
  "a11y/link-name": {
    rule_id: "a11y/link-name",
    source: "axe",
    vendor_rule_id: "link-name",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "2.4.4",
    title_template: "Links must have discernible text",
    description_template: "A link element has no accessible name.",
    recommendation:
      "Add visible link text, an aria-label, or aria-labelledby to each link so its purpose is clear.",
  },
  "a11y/button-name": {
    rule_id: "a11y/button-name",
    source: "axe",
    vendor_rule_id: "button-name",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "4.1.2",
    title_template: "Buttons must have an accessible name",
    description_template: "A button element has no text or accessible label.",
    recommendation: "Add visible button text, an aria-label, or aria-labelledby to each button.",
  },
  "a11y/landmark-one-main": {
    rule_id: "a11y/landmark-one-main",
    source: "axe",
    vendor_rule_id: "landmark-one-main",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: null,
    title_template: "Page must have one main landmark",
    description_template: "The page is missing a main landmark, or has more than one.",
    recommendation: "Wrap the primary content in a single <main> element.",
  },
  "a11y/region": {
    rule_id: "a11y/region",
    source: "axe",
    vendor_rule_id: "region",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: "1.3.6",
    title_template: "All page content must be contained in landmarks",
    description_template: "Content exists outside of landmark regions.",
    recommendation:
      "Wrap all content in landmark elements such as <main>, <nav>, <header>, or <footer>.",
  },
  "a11y/heading-order": {
    rule_id: "a11y/heading-order",
    source: "axe",
    vendor_rule_id: "heading-order",
    category: "a11y",
    default_severity: "minor",
    default_effort: "low",
    wcag: "1.3.1",
    title_template: "Heading levels must not be skipped",
    description_template: "Heading levels are not in sequential descending order.",
    recommendation: "Use heading levels in sequential order without skipping levels.",
  },
  "a11y/html-has-lang": {
    rule_id: "a11y/html-has-lang",
    source: "axe",
    vendor_rule_id: "html-has-lang",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "3.1.1",
    title_template: "html element must have a lang attribute",
    description_template: "The html element is missing a lang attribute.",
    recommendation: 'Add a lang attribute to the html element, for example lang="en".',
  },
  "a11y/html-lang-valid": {
    rule_id: "a11y/html-lang-valid",
    source: "axe",
    vendor_rule_id: "html-lang-valid",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "3.1.1",
    title_template: "html element must have a valid lang attribute",
    description_template:
      "The lang attribute value on the html element is not a valid BCP 47 language tag.",
    recommendation: "Set the lang attribute to a valid language tag such as en, fr, or de.",
  },
  "a11y/document-title": {
    rule_id: "a11y/document-title",
    source: "axe",
    vendor_rule_id: "document-title",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "2.4.2",
    title_template: "Documents must have a title element",
    description_template: "The page is missing a <title> element.",
    recommendation: "Add a descriptive <title> element that identifies the page content.",
  },
  "a11y/duplicate-id": {
    rule_id: "a11y/duplicate-id",
    source: "axe",
    vendor_rule_id: "duplicate-id",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: "4.1.1",
    title_template: "id attribute values must be unique",
    description_template: "Multiple elements share the same id value.",
    recommendation: "Ensure every id attribute value is unique within the page.",
  },
  "a11y/frame-title": {
    rule_id: "a11y/frame-title",
    source: "axe",
    vendor_rule_id: "frame-title",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: "2.4.1",
    title_template: "Frames must have a title attribute",
    description_template: "An iframe or frame element has no title attribute.",
    recommendation: "Add a descriptive title attribute to each iframe element.",
  },
  "a11y/input-button-name": {
    rule_id: "a11y/input-button-name",
    source: "axe",
    vendor_rule_id: "input-button-name",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "4.1.2",
    title_template: "Input buttons must have discernible text",
    description_template:
      "An input element of type button, submit, or reset has no accessible name.",
    recommendation: "Add a value attribute or aria-label to the input button.",
  },
  "a11y/input-image-alt": {
    rule_id: "a11y/input-image-alt",
    source: "axe",
    vendor_rule_id: "input-image-alt",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "1.1.1",
    title_template: "Image buttons must have alternative text",
    description_template: "An input element of type image has no alt attribute.",
    recommendation: "Add an alt attribute describing the button action to each image input.",
  },
  "a11y/meta-viewport": {
    rule_id: "a11y/meta-viewport",
    source: "axe",
    vendor_rule_id: "meta-viewport",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: "1.4.4",
    title_template: "Zooming and scaling must not be disabled",
    description_template: "The meta viewport tag disables user scaling.",
    recommendation: "Remove user-scalable=no and maximum-scale=1 from the meta viewport tag.",
  },
  "a11y/select-name": {
    rule_id: "a11y/select-name",
    source: "axe",
    vendor_rule_id: "select-name",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "4.1.2",
    title_template: "Select elements must have an accessible name",
    description_template: "A select element has no associated label.",
    recommendation: "Add a label element, aria-label, or aria-labelledby to each select element.",
  },
  "a11y/tabindex": {
    rule_id: "a11y/tabindex",
    source: "axe",
    vendor_rule_id: "tabindex",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: "2.1.1",
    title_template: "Positive tabindex values must not be used",
    description_template: "An element has a tabindex value greater than 0.",
    recommendation: "Remove tabindex values greater than 0 or replace them with tabindex=0.",
  },
  "a11y/valid-lang": {
    rule_id: "a11y/valid-lang",
    source: "axe",
    vendor_rule_id: "valid-lang",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: "3.1.2",
    title_template: "lang attribute must have a valid value",
    description_template: "An element has a lang attribute with an invalid BCP 47 language tag.",
    recommendation:
      "Set the lang attribute to a valid language tag on all elements where it is used.",
  },
  "a11y/aria-roles": {
    rule_id: "a11y/aria-roles",
    source: "axe",
    vendor_rule_id: "aria-roles",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: "4.1.2",
    title_template: "ARIA roles must conform to valid values",
    description_template: "An element has an invalid or abstract ARIA role.",
    recommendation: "Use only valid, non-abstract ARIA roles from the WAI-ARIA specification.",
  },
  "a11y/aria-required-attr": {
    rule_id: "a11y/aria-required-attr",
    source: "axe",
    vendor_rule_id: "aria-required-attr",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "4.1.2",
    title_template: "Required ARIA attributes must be provided",
    description_template: "An element with an ARIA role is missing required ARIA attributes.",
    recommendation: "Add all required attributes for the ARIA role applied to the element.",
  },
  "a11y/aria-allowed-attr": {
    rule_id: "a11y/aria-allowed-attr",
    source: "axe",
    vendor_rule_id: "aria-allowed-attr",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: "4.1.2",
    title_template: "ARIA attributes must be allowed for the element role",
    description_template: "An element has ARIA attributes that are not permitted for its role.",
    recommendation: "Remove ARIA attributes that are not valid for the element's role.",
  },
  "a11y/nested-interactive": {
    rule_id: "a11y/nested-interactive",
    source: "axe",
    vendor_rule_id: "nested-interactive",
    category: "a11y",
    default_severity: "major",
    default_effort: "medium",
    wcag: "4.1.3",
    title_template: "Interactive elements must not be nested",
    description_template: "An interactive element is nested inside another interactive element.",
    recommendation:
      "Restructure the markup so that interactive elements are not nested inside each other.",
  },
  "a11y/role-img-alt": {
    rule_id: "a11y/role-img-alt",
    source: "axe",
    vendor_rule_id: "role-img-alt",
    category: "a11y",
    default_severity: "critical",
    default_effort: "low",
    wcag: "1.1.1",
    title_template: "Elements with role=img must have alternative text",
    description_template: "An element with role=img has no accessible name.",
    recommendation: "Add an aria-label or aria-labelledby attribute to elements with role=img.",
  },
  "a11y/td-headers-attr": {
    rule_id: "a11y/td-headers-attr",
    source: "axe",
    vendor_rule_id: "td-headers-attr",
    category: "a11y",
    default_severity: "major",
    default_effort: "low",
    wcag: "1.3.1",
    title_template: "Table cells must use headers that refer to a valid id",
    description_template: "A td element has a headers attribute that does not match any th id.",
    recommendation:
      "Ensure each headers attribute value references the id of an existing th element.",
  },
};

export { axeCatalog };
export type { AxeCatalogEntry };
